## Feature Importance

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ncsr_clean.csv')
df.head() #First five observations

,Index,Y,Psychiatrist,Med doctor,Psychologist,Social worker,Mental health pro,Non med pro,Spiritual Advisor,Healer,...,D26Z,D26AA,D26BB,D26CC,D26DD,D26EE,D26FF,D26GG,D26HH,D26II
0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
1,17.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
2,18.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
3,28.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,32.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0

In [3]:
df = df[:294]

In [4]:
X = df.drop(['Index','Y'],1)
Y = df['Y']

In [10]:
from sklearn.ensemble import ExtraTreesClassifier
# fit an Extra Trees model to the data
model = ExtraTreesClassifier()
model.fit(X, Y)
# display the relative importance of each attribute
print(model.feature_importances_)

[0.01276237 0.01248205 0.00764947 0.00581512 0.00211397 0.00284957
 0.00674759 0.0076475  0.01931884 0.01313367 0.00941511 0.00952804
 0.00377118 0.01174021 0.00663123 0.01381405 0.02752884 0.01715007
 0.01666251 0.00254193 0.01004065 0.01272056 0.01740477 0.02089861
 0.01228414 0.01766635 0.01465516 0.01155412 0.0054126  0.00390833
 0.02242031 0.01407656 0.01602218 0.01408878 0.02309911 0.00594443
 0.01919678 0.0103439  0.026309   0.02021331 0.01022485 0.01675638
 0.00665269 0.00163844 0.00683738 0.00424669 0.01518227 0.01508786
 0.01315164 0.00711992 0.00731813 0.02193217 0.0086152  0.01099953
 0.0024829  0.00908277 0.00216808 0.01058182 0.00665251 0.01189191
 0.00907489 0.00861979 0.01242702 0.01058141 0.00845293 0.0046774
 0.00629703 0.00659704 0.         0.01326825 0.0069165  0.00448469
 0.00256083 0.01700616 0.00981865 0.00688836 0.01432165 0.0089771
 0.00566561 0.01256777 0.00838434 0.00795415 0.00684325 0.01192141
 0.01174966 0.0133282  0.00603332 0.02187434 0.00962027 0.00938996
 0.01157862 0.00570942 0.01022388]

In [11]:
cols = X.columns.tolist()
imp = pd.DataFrame(list(zip(cols, model.feature_importances_)), 
             columns=["predictor","importance"])

In [12]:
imp_des = imp.sort_values(by='importance', ascending=0)
imp_des.head(10)

                     predictor  importance
16                       HHINC    0.027529
38                         PH1    0.026309
34                         EM1    0.023099
30                         SU1    0.022420
51                        D37A    0.021932
87                       D26DD    0.021874
23  DIVORCED_SEPARATED_WIDOWED    0.020899
39                         PH2    0.020213
8                    Counselor    0.019319
36                       FD25A    0.019197